smtp:
  build: smtp-docker

db:
  build: mysql-docker
  volumes_from:
    - mysql-data

forum:
  build: fluxbb-docker
  ports:
    - "8080:80"
  volumes_from:
    - fluxbb-data
  links:
    - db
    - smtp
  environment:
    VIRTUAL_HOST: forum.*

phpadmin:
  image: corbinu/docker-phpmyadmin
  ports:
    - "8081:80"
  links:
    - db:mysql
  environment:
    VIRTUAL_HOST: phpadmin.*

wiki:
  build: mediawiki-docker
  ports:
    - "8082:80"
  volumes_from:
    - mediawiki-data
  links:
    - db
    - smtp
  environment:
    VIRTUAL_HOST: wiki.*

map:
  build: map-docker
  ports:
    - "8083:80"
  environment:
    VIRTUAL_HOST: map.*
  volumes:
    - ./online_chart:/data

webhook:
  build: webhook-docker
  ports:
    - "8084:80"
  environment:
    VIRTUAL_HOST: webhook.*
    USE_PROXYFIX: "true"
    DEBUG: "true"
  volumes:
    - ./github-webhook-handler:/usr/src/app
    - ./repos.json:/data/repos.json
    - ./github_token:/data/github_token
    - /var/run/docker.sock:/var/run/docker.sock

tiles:
  build: tiles-docker
  ports:
    - "8085:80"
  environment:
    VIRTUAL_HOST: tiles.*,t1.*
  volumes:
    - /home/axel/Condor/alpha.openseamap.org/t1/tiles:/data

proxy:
  build: nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
